<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestUserService-20180611110309" tests="6" time="1.440">
	<testcase classname="TestUserService" name="test_add_user" time="0.102"/>
	<testcase classname="TestUserService" name="test_book_movie" time="0.151"/>
	<testcase classname="TestUserService" name="test_user_not_found" time="0.091"/>
	<testcase classname="TestUserService" name="test_user_records" time="0.143"/>
	<testcase classname="TestUserService" name="test_view_user_booking" time="0.550"/>
	<testcase classname="TestUserService" name="test_user_suggested" time="0.403">
		<error message="False is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "user.py", line 121, in test_user_suggested
    self.assertTrue(item==actual_reply)
AssertionError: False is not true
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
